### ISSUE TITLE
Failure creating unreal-gold-data from cd

### ISSUE THREAD

**Issue by E-werd** [a-detiste/game-data-packager#5]
I was unsure where else to file this issue, please point me in the right direction if this is incorrect.

[unreal-gold-error-gdp.txt](https://github.com/a-detiste/game-data-packager/files/957027/unreal-gold-error-gdp.txt)

Attached above is the command and output that I am having an issue with.  It would appear that the hashes just are not in place for my CD version.  This is a retail Unreal Gold CD, packaged in the same box as UT99 (which seemed to create unreal-ut99-shared-data just fine).

**Comment by smcv** [comment]
The main bug tracker for game-data-packager is the [Debian bug tracking system](https://www.debian.org/Bugs/).

**Comment by smcv** [comment]
You seem to have three issues here:

Some of the files on your CD are not a version we know about. To help us to resolve this, please run:

```
game-data-packager make-template /media/ewymer/UNREAL_GOLD/
```

and send the output to game-data-packager at packages.debian.org or a Debian bug report, or attach it here.

If you can provide any additional information about the version of Unreal on this CD (a version number from a README, a copyright date, the country it was sold in, the publisher on the packaging, whether it's from a budget re-release, that sort of thing) that would also be helpful.

Some of the files we expect to be present (mostly sounds) also seem to be completely missing, without even having a file of the same name but different content. The `make-template` output would give us more clues about where we can find those.

Finally, game-data-packager seems to think it should be trying to download `UnrealGoldPatch227i.zip`. I'm not quite sure why.

**Comment by a-detiste** [comment]
I'm keeping this because UI is much more usefull than Alioth's CGI;
but I now see I can disable the bug tracker; maybe adding a README.md
would be nice too.

**Comment by E-werd** [comment]
Files:
[unreal_gold_manifest.txt](https://github.com/a-detiste/game-data-packager/files/960236/unreal_gold_manifest.txt)
[unreal_gold_template.txt](https://github.com/a-detiste/game-data-packager/files/960235/unreal_gold_template.txt)

Above are two things.  The first is the file "/SYSTEM/Manifest.ini" from the CD which reveals the version to be Unreal Gold 226b

The second file is the template generated from make-template.

**Comment by smcv** [comment]
> Some of the files we expect to be present (mostly sounds) also seem to be completely missing

From the make-template output, it looks like they're in `SOUNDS/int`. Thanks, we can merge that information.

**Comment by smcv** [comment]
I've forwarded this information to a Debian bug report. I'll update `unreal.yaml` with the new information soon.

**Comment by smcv** [comment]
@E-werd: please try game-data-packager version 50 from Debian experimental (it should work fine on testing/unstable, and probably also on stable), or the `debian/50` tag from this repository. That version should work with your Unreal Gold 226b CD.

Please comment here if you still get warnings or errors.

Version 50 should also be able to package UT99 using the unofficial UTPG patch mirrored at e.g. <http://unreal4fun.de/e107/download.php?view.21> and <http://toxiccode.com/ut/files.html>, so try that too if you're interested in UT99. If you use a modern audio API like PulseAudio or ALSA you'll probably need to install `osspd` to get working audio, because the UT99 binaries are so old that they default to OSS.
